version: '3.2'
services:
    zookeeper:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
    microservice:
        build: tf-idf-distributed/
        links:
            - "zookeeper:zookeeper"
        ports:
            - "8083-8085:8083"
    front-end:
        build: distributed-search-front/
        links:
            - "zookeeper:zookeeper"
        ports:
            - "8087:8087"