version: '3.2'
services:
    zookeeper:
        image: zookeeper
        restart: always
        volumes:
            - ./zoo1/data:/data
            - ./zoo1/datalog:/datalog
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1

    microservice:
        build: ./tf-idf-distributed
        ports:
          - "8083:8083"
        volumes:
            - ./ms1/.m2:/root/.m2
        links:
          - zookeeper
        depends_on:
          - zookeeper
