apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-volume-claim
spec:
  volumeName: books-volume
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: books-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/resources/
    type: DirectoryOrCreate